version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: jkim
      POSTGRES_PASSWORD: Tkfkdgo3@
      POSTGRES_DB: Dashboard
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://jkim:Tkfkdgo3%40@localhost:5432/postgres
    depends_on:
      - postgres

volumes:
  postgres_data: